name: optibill
description: An optical shop billing and management application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your Flutter stable version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3 # Local database
  hive_flutter: ^1.1.0 # Flutter integration for Hive
  uuid: ^4.4.0 # For generating unique IDs
  intl: ^0.19.0 # For date/time and currency formatting
  pdf: ^3.10.8 # For PDF generation
  printing: ^5.12.0 # For sharing/saving PDFs
  path_provider: ^2.1.3 # For getting application document directory
  google_sign_in: ^6.2.1 # For Google authentication
  googleapis: ^12.0.0 # For Google APIs, including Drive
  http: ^1.2.0 # Changed from ^1.2.1 to resolve SDK conflict
  collection: ^1.18.0 # Added for firstWhereOrNull
  excel: ^2.1.0 # New: For Excel file generation
  permission_handler: ^11.3.1
  connectivity_plus: ^5.0.2 # Add this line
  shared_preferences: ^2.2.2 # Add this line



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1 # For generating Hive adapters
  build_runner: ^2.4.9 # For running code generators
  flutter_launcher_icons: ^0.13.1 # For generating app icons

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/optibill_icon.png"
  min_sdk_android: 21
  
  # Web configuration
  web:
    generate: true
    image_path: "assets/icon/optibill_icon.png"
    background_color: "#2196F3"  # Blue theme for optical shop
    theme_color: "#1976D2"       # Darker blue
  
  # Windows configuration
  windows:
    generate: true
    image_path: "assets/icon/optibill_icon.png"
    icon_size: 48
  
  # macOS configuration
  macos:
    generate: true
    image_path: "assets/icon/optibill_icon.png"


flutter:
  uses-material-design: true

   # Assets configuration (add this section)
  assets:
    - assets/icon/
