import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart'; // For getting app document directory

// Import your generated Hive adapters
import 'package:optibill/models/frame.dart';
import 'package:optibill/models/lens.dart';
import 'package:optibill/models/invoice_item.dart';
import 'package:optibill/models/invoice.dart';

// Import your screens
import 'package:optibill/screens/login_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  final appDocumentDir = await getApplicationDocumentsDirectory();
  await Hive.initFlutter(appDocumentDir.path);

  // Register Hive Adapters
  // These adapters will be generated by `hive_generator`
  Hive.registerAdapter(FrameAdapter());
  Hive.registerAdapter(LensAdapter());
  Hive.registerAdapter(InvoiceItemAdapter());
  Hive.registerAdapter(InvoiceAdapter());

  // Open your Hive boxes
  await Hive.openBox<Frame>('frames');
  await Hive.openBox<Lens>('lenses');
  await Hive.openBox<Invoice>('invoices');
  // Add a box for user credentials (username/password)
  await Hive.openBox('user_credentials');

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'OptiBill',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        fontFamily: 'Inter', // Using Inter font as requested
      ),
      home: const LoginScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
